import React from "react";
import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiPython,
  SiTensorflow,
  SiDocker,
  SiKubernetes,
  SiAmazon,
  SiCss3,
  SiHtml5,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiGraphql,
  SiGit,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiFigma,
  SiRedux,
  SiExpress,
  SiDjango,
  SiFlask,
  SiRuby,
  SiPhp,
  SiRust,
  SiGo,
  SiSwift,
  SiKotlin,
  SiFirebase,
  SiVercel,
  SiNetlify,
  SiGithub,
  SiGitlab,
  SiRedis,
  SiNginx,
  SiJenkins,
  SiTerraform,
} from "react-icons/si";
import { TbBrandReactNative, TbBrandCpp } from "react-icons/tb";
import {
  FaDatabase,
  FaChartBar,
  FaShieldAlt,
  FaLock,
  FaNetworkWired,
  FaBrain,
  FaRobot,
  FaEye,
  FaCode,
  FaJava,
  FaCloud,
} from "react-icons/fa";

interface SkillBadgeProps {
  skill: string;
  isDark?: boolean;
}

const skillBrandColors: Record<string, string> = {
  React: "#61dafb",
  TypeScript: "#3178c6",
  JavaScript: "#f7df1e",
  CSS: "#264de4",
  HTML: "#e34f26",
  "Next.js": "#000000",
  Vue: "#41b883",
  Angular: "#dd0031",
  "React Native": "#61dafb",
  Redux: "#764abc",
  Figma: "#f24e1e",
  "Node.js": "#83cd29",
  Python: "#3776ab",
  Express: "#444444",
  Django: "#092e20",
  Flask: "#444444",
  Ruby: "#cc342d",
  PHP: "#777bb4",
  Java: "#f89820",
  "C++": "#00599c",
  "C#": "#178600",
  Rust: "#dea584",
  Go: "#00add8",
  Swift: "#f05138",
  Kotlin: "#7f52ff",
  Dart: "#0175c2",
  Bash: "#4eaa25",
  PowerShell: "#5391fe",
  R: "#276dc3",
  SQL: "#2f74c0",
  Databases: "#4b8bbe",
  MongoDB: "#47a248",
  PostgreSQL: "#336791",
  MySQL: "#00758f",
  GraphQL: "#e10098",
  Redis: "#d82c20",
  AWS: "#ff9900",
  Docker: "#2496ed",
  Kubernetes: "#326ce5",
  Firebase: "#ffcb2b",
  Vercel: "#000000",
  Netlify: "#00c7b7",
  Nginx: "#009639",
  Jenkins: "#d33833",
  Terraform: "#844fba",
  TensorFlow: "#ff6f00",
  "Data Visualization": "#336791",
  Statistics: "#336791",
  Excel: "#217346",
  FastAPI: "#05998a",
  Rails: "#cc0000",
  Spring: "#6db33f",
  "ASP.NET": "#512bd4",
  "Express.js": "#444444",
  "Vue.js": "#41b883",
  Svelte: "#ff3e00",
  Flutter: "#02569b",
  "Hugging Face": "#ffcc00",
  LangChain: "#0f9d58",
  "OpenAI API": "#74aa9c",
  Anthropic: "#121212",
  PyTorch: "#ee4c2c",
  "Scikit-learn": "#f89939",
  Pandas: "#130754",
  NumPy: "#013243",
  Matplotlib: "#11557c",
  Tableau: "#e97627",
  Jupyter: "#f37626",
  "Apache Spark": "#e25a1c",
  Ansible: "#ee0000",
  "Android Studio": "#3ddc84",
  Metasploit: "#1a9cff",
  "Burp Suite": "#f46d25",
  Wireshark: "#1679a7",
  Nmap: "#1b3b6f",
  "Adobe CC": "#ed1c24",
  Sketch: "#f7b500",
  Blender: "#e87d0d",
  "Adobe XD": "#ff61f6",
  "Prototype.io": "#4a90e2",
  InVision: "#ff3366",
  CUDA: "#76b900",
  Keras: "#d00000",
  Xcode: "#1575f9",
};

const skillIconMap: Record<string, React.ReactNode> = {
  React: <SiReact className="w-3 h-3" />,
  TypeScript: <SiTypescript className="w-3 h-3" />,
  JavaScript: <SiJavascript className="w-3 h-3" />,
  CSS: <SiCss3 className="w-3 h-3" />,
  HTML: <SiHtml5 className="w-3 h-3" />,
  "Next.js": <SiNextdotjs className="w-3 h-3" />,
  Vue: <SiVuedotjs className="w-3 h-3" />,
  Angular: <SiAngular className="w-3 h-3" />,
  "React Native": <TbBrandReactNative className="w-3 h-3" />,
  Redux: <SiRedux className="w-3 h-3" />,
  "UX/UI": <SiFigma className="w-3 h-3" />,
  Figma: <SiFigma className="w-3 h-3" />,
  "Node.js": <SiNodedotjs className="w-3 h-3" />,
  Python: <SiPython className="w-3 h-3" />,
  Express: <SiExpress className="w-3 h-3" />,
  Django: <SiDjango className="w-3 h-3" />,
  Flask: <SiFlask className="w-3 h-3" />,
  Ruby: <SiRuby className="w-3 h-3" />,
  PHP: <SiPhp className="w-3 h-3" />,
  Java: <FaJava className="w-3 h-3" />,
  "C++": <TbBrandCpp className="w-3 h-3" />,
  "C#": <FaCode className="w-3 h-3" />,
  Rust: <SiRust className="w-3 h-3" />,
  Go: <SiGo className="w-3 h-3" />,
  Swift: <SiSwift className="w-3 h-3" />,
  Kotlin: <SiKotlin className="w-3 h-3" />,
  Dart: <FaCode className="w-3 h-3" />,
  Bash: <FaCode className="w-3 h-3" />,
  PowerShell: <FaCode className="w-3 h-3" />,
  R: <FaChartBar className="w-3 h-3" />,
  Scala: <FaCode className="w-3 h-3" />,
  Julia: <FaCode className="w-3 h-3" />,
  CUDA: <FaCode className="w-3 h-3" />,
  YAML: <FaCode className="w-3 h-3" />,
  HCL: <FaCode className="w-3 h-3" />,
  C: <FaCode className="w-3 h-3" />,
  Databases: <FaDatabase className="w-3 h-3" />,
  MongoDB: <SiMongodb className="w-3 h-3" />,
  PostgreSQL: <SiPostgresql className="w-3 h-3" />,
  MySQL: <SiMysql className="w-3 h-3" />,
  SQL: <FaDatabase className="w-3 h-3" />,
  GraphQL: <SiGraphql className="w-3 h-3" />,
  Redis: <SiRedis className="w-3 h-3" />,
  AWS: <SiAmazon className="w-3 h-3" />,
  Docker: <SiDocker className="w-3 h-3" />,
  Kubernetes: <SiKubernetes className="w-3 h-3" />,
  Infrastructure: <FaNetworkWired className="w-3 h-3" />,
  Firebase: <SiFirebase className="w-3 h-3" />,
  Vercel: <SiVercel className="w-3 h-3" />,
  Netlify: <SiNetlify className="w-3 h-3" />,
  Nginx: <SiNginx className="w-3 h-3" />,
  Jenkins: <SiJenkins className="w-3 h-3" />,
  Terraform: <SiTerraform className="w-3 h-3" />,
  TensorFlow: <SiTensorflow className="w-3 h-3" />,
  ML: <FaBrain className="w-3 h-3" />,
  "Deep Learning": <FaRobot className="w-3 h-3" />,
  NLP: <FaBrain className="w-3 h-3" />,
  "Computer Vision": <FaEye className="w-3 h-3" />,
  "Data Visualization": <FaChartBar className="w-3 h-3" />,
  Visualization: <FaChartBar className="w-3 h-3" />,
  Statistics: <FaChartBar className="w-3 h-3" />,
  Excel: <FaChartBar className="w-3 h-3" />,
  Security: <FaShieldAlt className="w-3 h-3" />,
  Encryption: <FaLock className="w-3 h-3" />,
  "Penetration Testing": <FaShieldAlt className="w-3 h-3" />,
  Compliance: <FaShieldAlt className="w-3 h-3" />,
  "Incident Response": <FaShieldAlt className="w-3 h-3" />,
  APIs: <FaCode className="w-3 h-3" />,
  Testing: <FaCode className="w-3 h-3" />,
  "System Design": <FaNetworkWired className="w-3 h-3" />,
  Architecture: <FaNetworkWired className="w-3 h-3" />,
  SDLC: <FaCode className="w-3 h-3" />,
  Git: <SiGit className="w-3 h-3" />,
  GitHub: <SiGithub className="w-3 h-3" />,
  GitLab: <SiGitlab className="w-3 h-3" />,
  Flutter: <FaCode className="w-3 h-3" />,
  "Hugging Face": <FaBrain className="w-3 h-3" />,
  LangChain: <FaBrain className="w-3 h-3" />,
  "OpenAI API": <FaBrain className="w-3 h-3" />,
  Anthropic: <FaBrain className="w-3 h-3" />,
  PyTorch: <SiPython className="w-3 h-3" />,
  "Scikit-learn": <SiPython className="w-3 h-3" />,
  Keras: <SiPython className="w-3 h-3" />,
  Pandas: <SiPython className="w-3 h-3" />,
  NumPy: <SiPython className="w-3 h-3" />,
  Matplotlib: <FaChartBar className="w-3 h-3" />,
  Tableau: <FaChartBar className="w-3 h-3" />,
  Jupyter: <SiPython className="w-3 h-3" />,
  "Apache Spark": <FaDatabase className="w-3 h-3" />,
  Ansible: <FaNetworkWired className="w-3 h-3" />,
  FastAPI: <SiPython className="w-3 h-3" />,
  Rails: <SiRuby className="w-3 h-3" />,
  Spring: <FaJava className="w-3 h-3" />,
  "ASP.NET": <FaCode className="w-3 h-3" />,
  "Express.js": <SiNodedotjs className="w-3 h-3" />,
  "Vue.js": <SiVuedotjs className="w-3 h-3" />,
  Svelte: <FaCode className="w-3 h-3" />,
  Xcode: <FaCode className="w-3 h-3" />,
  "Android Studio": <FaCode className="w-3 h-3" />,
  Metasploit: <FaShieldAlt className="w-3 h-3" />,
  "Burp Suite": <FaShieldAlt className="w-3 h-3" />,
  Wireshark: <FaNetworkWired className="w-3 h-3" />,
  Nmap: <FaNetworkWired className="w-3 h-3" />,
  "Adobe CC": <FaCode className="w-3 h-3" />,
  Sketch: <FaCode className="w-3 h-3" />,
  Blender: <FaCode className="w-3 h-3" />,
  "Adobe XD": <FaCode className="w-3 h-3" />,
  "Prototype.io": <FaCode className="w-3 h-3" />,
  InVision: <FaCode className="w-3 h-3" />,
  "Native Apps": <FaCode className="w-3 h-3" />,
  "Cross-platform": <FaCode className="w-3 h-3" />,
  "UI Design": <SiFigma className="w-3 h-3" />,
  "Visual Design": <FaCode className="w-3 h-3" />,
  Branding: <FaCode className="w-3 h-3" />,
  Typography: <FaCode className="w-3 h-3" />,
  Layout: <FaCode className="w-3 h-3" />,
  "User Research": <FaCode className="w-3 h-3" />,
  Wireframing: <FaCode className="w-3 h-3" />,
  Prototyping: <FaCode className="w-3 h-3" />,
  LLMs: <FaBrain className="w-3 h-3" />,
  "Prompt Engineering": <FaBrain className="w-3 h-3" />,
  "AI Ethics": <FaBrain className="w-3 h-3" />,
  "Production Systems": <FaNetworkWired className="w-3 h-3" />,
  "Neural Networks": <FaBrain className="w-3 h-3" />,
  "Model Training": <FaBrain className="w-3 h-3" />,
  MLOps: <FaBrain className="w-3 h-3" />,
  "Statistical Analysis": <FaChartBar className="w-3 h-3" />,
  "Predictive Modeling": <FaChartBar className="w-3 h-3" />,
  "Big Data": <FaDatabase className="w-3 h-3" />,
  ETL: <FaDatabase className="w-3 h-3" />,
  "Design Thinking": <FaCode className="w-3 h-3" />,
  "Color Theory": <FaCode className="w-3 h-3" />,
  Composition: <FaCode className="w-3 h-3" />,
  Motion: <FaCode className="w-3 h-3" />,
  "User Psychology": <FaBrain className="w-3 h-3" />,
  "Information Architecture": <FaCode className="w-3 h-3" />,
  Accessibility: <FaCode className="w-3 h-3" />,
  "A/B Testing": <FaChartBar className="w-3 h-3" />,
};

export const SkillBadge: React.FC<SkillBadgeProps> = ({ skill }) => {
  const icon = skillIconMap[skill];
  const defaultIconColor = "#008080";
  const iconColor = skillBrandColors[skill] || defaultIconColor;
  const coloredIcon =
    icon && React.isValidElement(icon)
      ? React.cloneElement(icon, { style: { color: iconColor } })
      : icon;

  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full border border-gray-900/10 bg-gray-900/[0.04] px-2.5 py-1 text-xs text-gray-700 dark:border-white/10 dark:bg-white/10 dark:text-gray-200"
    >
      {coloredIcon && <span className="flex-shrink-0">{coloredIcon}</span>}
      <span>{skill}</span>
    </span>
  );
};
